package main

import (
	"testing"
	"time"
)

var tests = []struct {
	Operation   string
	Measurement int
	Original    string
	Padded      string
	OTP         string
	Encrypted   string
	MD5         string
}{
	{
		Operation:   "Minotaur",
		Measurement: 1,
		Original:    "TWO O CLOCK FOUR MINUTES AND THIRTY EIGHT SECONDS",
		Padded:      "TWOXOXCLOCKXFOURXMINUTESXANDXTHIRTYXEIGHTXSECONDS",
		OTP:         "ZPCDKCAPANHLJTXFBNZEJOHZELDOJPOLPVGLXNMLPBKPNPBQJ",
		Encrypted:   "SLQAYZCAOPRIOHRWYZHRDHLRBLQRGIVTGOEIBVSSIYCTPDOTB",
		MD5:         "e31492102271d3d2dfb46e12bb3643f0",
	},
	{
		Operation:   "Minotaur",
		Measurement: 2,
		Original:    " THREE O  CLOCK ONE MINUTE AND FIFTY FIVE SECONDS",
		Padded:      "XTHREEXOXXCLOCKXONEXMINUTEXANDXFIFTYXFIVEXSECONDS",
		OTP:         "VBSPJANJEQMGHQDYQNYDJVULFTCGQTSDKGVXRSDFCHABJMZXV",
		Encrypted:   "SUZGNEKXBNORVSNVEACAVDHFYXZGDWPISLOVOXLAGESFLAMAN",
		MD5:         "6b7ca401083b34628db954c1e8b1c5de",
	},
	{
		Operation:   "Minotaur",
		Measurement: 3,
		Original:    " FOUR O  CLOCK  THREE  MINUTES AND TWENTY SECONDS",
		Padded:      "XFOURXOXXCLOCKXXTHREEXXMINUTESXANDXTWENTYXSECONDS",
		OTP:         "OISLXYTPMVBXENULQEXVIKUFGAHODYOZWRTEZQJXTXRWQCBHZ",
		Encrypted:   "LNGFOVHMJXMLGXRIJLOZMHRRONBHHQLZJUQXVUWQRUJASQOKR",
		MD5:         "f0f8fd5d99d227caaa3d02bad43179cd",
	},
	{
		Operation:   "Minotaur",
		Measurement: 4,
		Original:    "FIVE O CLOCK TWO MINUTES AND TWENTY SEVEN SECONDS",
		Padded:      "FIVEXOXCLOCKXTWOXMINUTESXANDXTWENTYXSEVENXSECONDS",
		OTP:         "KZUQKFADYLAGSRZMFKTQYGPDDJXIHDKGIWATFBLGZZEFWPWWN",
		Encrypted:   "PHPUHTXFJZCQPKVACWBDSZTVAJKLEWGKVPYQXFGKMWWJYDJZF",
		MD5:         "029d2072bd788bac6ebfcf431c590001",
	},
	{
		Operation:   "Cassandra - Sydney",
		Measurement: 1,
		Original:    "ONE  MINUTE   THIRTY FOUR  SECONDS   PAST  ONE  O  CLOCK   ",
		Padded:      "ONEXXMINUTEXXXTHIRTYXFOURXXSECONDSXXXPASTXXONEXXOXXCLOCKXXX",
		OTP:         "LWIAXSXZNPDJAKBKSQAVRXDHFDDKVAMECERVZDSOHCEPTLEMNLFPRHNMDQG",
		Encrypted:   "ZJMXUEFMHIHGXHURAHTTOCRBWAACZCARFWOSWSSGAZBDGPBJBICRCVPWAND",
		MD5:         "64389AE19DEBAB3B7E5D668C751FD545",
	},
	{
		Operation:   "Cassandra - Sydney",
		Measurement: 2,
		Original:    "  TWO  O  CLOCK AND FOUR  MINUTES  AND FIFTY FIVE SECONDS  ",
		Padded:      "XXTWOXXOXXCLOCKXANDXFOURXXMINUTESXXANDXFIFTYXFIVEXSECONDSXX",
		OTP:         "YMBGTLBMLYGNKAFAYTQMJNFMFGBEYFQURUGAHVCDUIXTTOFZSNPVBGQEWWE",
		Encrypted:   "VJUCHIYAIVIYYCPXYGTJOBZDCDNMLZJYJRDAUYZICNQRQTNUWKHZDUDHOTB",
		MD5:         "544444F7085EC9C2BD6152C25E808E2D",
	},
	{
		Operation:   "Cassandra - Sydney",
		Measurement: 3,
		Original:    "   THREE  MINUTES   FIFTY TWO  SECONDS PAST THREE O CLOCK  ",
		Padded:      "XXXTHREEXXMINUTESXXXFIFTYXTWOXXSECONDSXPASTXTHREEXOXCLOCKXX",
		OTP:         "XQMQHNDRAKICVDGBAQTIIKJPYLMSPIJPPMAEQNQBLOSVXXBVSLOYONKQIJB",
		Encrypted:   "UNJJOEHVXHUKIXZFSNQFNSOIWIFODFGHTOORTFNQLGLSQESZWICVQYYSSGY",
		MD5:         "15BF98576D8B1D2D4A441643C4550323",
	},
	{
		Operation:   "Cassandra - Milan",
		Measurement: 1,
		Original:    "  FIFTY  FIVE SECONDS   AND   THREE  MINUTES  AFTER   SEVEN",
		Padded:      "XXFIFTYXXFIVEXSECONDSXXXANDXXXTHREEXXMINUTESXXAFTERXXXSEVEN",
		OTP:         "TRTRBRYFRYVXMARIWQMSAQBZAZPFQFFHDIZDXTZDUDHLFSFUANESJGZQJIK",
		Encrypted:   "QOYZGKWCODDSQXJMYEZVSNYWAMSCNCYOUMDAUFHQOWLDCPFZTRVPGDRUEMX",
		MD5:         "0E83F2DFE0B755CCF2CA0413F48732C1",
	},
	{
		Operation:   "Cassandra - Milan",
		Measurement: 2,
		Original:    "  EIGHT O CLOCK   TWO  MINUTES AND   FIFTY   FOUR   SECONDS",
		Padded:      "XXEIGHTXOXCLOCKXXXTWOXXMINUTESXANDXXXFIFTYXXXFOURXXXSECONDS",
		OTP:         "PCLYGZFEHWUMGWYUFXYVUZBQVNWLLOYRFEQNQAZDKEKUHURHNIHTNINSQZD",
		Encrypted:   "MZPGMGYBVTWXUYIRCURRIWYCDAQEPGVRSHNKNFHIDCHREZFBEFEQFMPGDCV",
		MD5:         "3BA87D382EE137FC9D6737437F57B550",
	},
	{
		Operation:   "Cassandra - Milan",
		Measurement: 3,
		Original:    "MEASUREMENT THREE  IS  AT  NINE  O THREE AND THIRTY SECONDS",
		Padded:      "MEASUREMENTXTHREEXXISXXATXXNINEXXOXTHREEXANDXTHIRTYXSECONDS",
		OTP:         "STBIPKMHJWTPGRIJQUELXPUUDVBEMMIDOLNZSNPHJOOKZPANTFBKOGEKAAV",
		Encrypted:   "EXBAJBQTNJMMZYZNURBTPMRUWSYRUZMALZKSZETLGOBNWIHVKYZHGKGYNDN",
		MD5:         "13084003CF687FA0FEE313161767BF07",
	},
}

func TestEncode(t *testing.T) {
	tests := []struct {
		Measurement int
		Time        time.Time
		Format      Format
		Expect      string
	}{
		{
			1, time.Date(2000, 1, 1, 14, 4, 38, 0, time.Local),
			FMinator,
			"TWO O CLOCK FOUR MINUTES AND THIRTY EIGHT SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 15, 1, 55, 0, time.Local),
			FMinator,
			"THREE O CLOCK ONE MINUTE AND FIFTY FIVE SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 16, 3, 20, 0, time.Local),
			FMinator,
			"FOUR O CLOCK THREE MINUTES AND TWENTY SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 17, 2, 27, 0, time.Local),
			FMinator,
			"FIVE O CLOCK TWO MINUTES AND TWENTY SEVEN SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 8, 2, 54, 0, time.Local),
			FMinator,
			"EIGHT O CLOCK TWO MINUTES AND FIFTY FOUR SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 1, 1, 34, 0, time.Local),
			FCassandraSydney1,
			"ONE MINUTE THIRTY FOUR SECONDS PAST ONE O CLOCK",
		},
		{
			1, time.Date(2000, 1, 1, 3, 3, 52, 0, time.Local),
			FCassandraSydney1,
			"THREE MINUTES FIFTY TWO SECONDS PAST THREE O CLOCK",
		},
		{
			1, time.Date(2000, 1, 1, 14, 4, 55, 0, time.Local),
			FCassandraSydney2,
			"TWO O CLOCK AND FOUR MINUTES AND FIFTY FIVE SECONDS",
		},
		{
			1, time.Date(2000, 1, 1, 19, 3, 55, 0, time.Local),
			FCassandraMilan1,
			"FIFTY FIVE SECONDS AND THREE MINUTES AFTER SEVEN",
		},
		{
			3, time.Date(2000, 1, 1, 21, 3, 30, 0, time.Local),
			FCassandraMilan3,
			"MEASUREMENT THREE IS AT NINE O THREE AND THIRTY SECONDS",
		},
	}

	for i, test := range tests {
		if got := test.Format.Encode(test.Measurement, test.Time); test.Expect != string(got) {
			t.Errorf("[%d] Expected %s; Got %s", i, test.Expect, got)
		}
	}
}
