package main

var Numbers = [][]byte{
	[]byte(`ZERO`),
	[]byte(`ONE`),
	[]byte(`TWO`),
	[]byte(`THREE`),
	[]byte(`FOUR`),
	[]byte(`FIVE`),
	[]byte(`SIX`),
	[]byte(`SEVEN`),
	[]byte(`EIGHT`),
	[]byte(`NINE`),
	[]byte(`TEN`),
	[]byte(`ELEVEN`),
	[]byte(`TWELVE`),
	[]byte(`THIRTEEN`),
	[]byte(`FOURTEEN`),
	[]byte(`FIFTEEN`),
	[]byte(`SIXTEEN`),
	[]byte(`SEVENTEEN`),
	[]byte(`EIGHTEEN`),
	[]byte(`NINETEEN`),
	[]byte(`TWENTY`),
	[]byte(`TWENTY ONE`),
	[]byte(`TWENTY TWO`),
	[]byte(`TWENTY THREE`),
	[]byte(`TWENTY FOUR`),
	[]byte(`TWENTY FIVE`),
	[]byte(`TWENTY SIX`),
	[]byte(`TWENTY SEVEN`),
	[]byte(`TWENTY EIGHT`),
	[]byte(`TWENTY NINE`),
	[]byte(`THIRTY`),
	[]byte(`THIRTY ONE`),
	[]byte(`THIRTY TWO`),
	[]byte(`THIRTY THREE`),
	[]byte(`THIRTY FOUR`),
	[]byte(`THIRTY FIVE`),
	[]byte(`THIRTY SIX`),
	[]byte(`THIRTY SEVEN`),
	[]byte(`THIRTY EIGHT`),
	[]byte(`THIRTY NINE`),
	[]byte(`FORTY`),
	[]byte(`FORTY ONE`),
	[]byte(`FORTY TWO`),
	[]byte(`FORTY THREE`),
	[]byte(`FORTY FOUR`),
	[]byte(`FORTY FIVE`),
	[]byte(`FORTY SIX`),
	[]byte(`FORTY SEVEN`),
	[]byte(`FORTY EIGHT`),
	[]byte(`FORTY NINE`),
	[]byte(`FIFTY`),
	[]byte(`FIFTY ONE`),
	[]byte(`FIFTY TWO`),
	[]byte(`FIFTY THREE`),
	[]byte(`FIFTY FOUR`),
	[]byte(`FIFTY FIVE`),
	[]byte(`FIFTY SIX`),
	[]byte(`FIFTY SEVEN`),
	[]byte(`FIFTY EIGHT`),
	[]byte(`FIFTY NINE`),
	[]byte(`SIXTY`),
}
